### ISSUE TITLE
support package-recursive search

### ISSUE THREAD

**Issue by rogpeppe** [mvdan/gogrep#11]
It's useful to be able to search a package and all its dependencies too.
Perhaps a "-r" flag could enable this.

**Comment by mvdan** [comment]
How useful would this be as opposed to `./...`? Should it include `std`?

**Comment by rogpeppe** [comment]
Much more useful - it's basically a whole-program search. I'd include std only with a special flag.

**Comment by mvdan** [comment]
I've added it without any `std` magic. Let me know if you still think that's worthwhile adding. I guess I could do it by checking if it's in `GOROOT`.

I could only see an ease of use value in it (avoiding piping through `grep`), as it would usually be a minor hit in performance.
