### ISSUE TITLE
matcher does not match some expressions that it should

### ISSUE THREAD

**Issue by rogpeppe** [mvdan/gogrep#18]
Two test cases that fail:

		{"print($*_, $a, $*_, $a_)", "print(a, b, c, b, d)", 1},
		{"$a; $*_; $a", "a; b; c; b", 1},

**Comment by mvdan** [comment]
This is an interesting one. I think I know why the second one is happening.

**Comment by mvdan** [comment]
Second one fixed, my hunch was right.

**Comment by mvdan** [comment]
Reduced version of the former: `{"print($*_, $b)", "print(a, b, c)", 1},`
