### ISSUE TITLE
Add an "any number of" wildcard

### ISSUE THREAD

**Issue by mvdan** [mvdan/gogrep#2]
We use `$x` to match any node. We should introduce a form to match any number of nodes in a list, to allow for stuff like:

    if $cond { $<any number of statements> }
    call(arg1, $<any number of expressions>)

I initially thought of `$x...`, but since `expr...` is valid Go, it's not a good idea. Perhaps `$x*`, which resembles a regular expression.

**Comment by rogpeppe** [comment]
Note that `$x*` is also valid Go, so I'm not sure that works any better than $x... (which was also my first thought).

Perhaps make the suffix significant only if it isn't separated from the $x by any whitespace?

**Comment by mvdan** [comment]
Ah, you're right. Yes, I was thinking with whitespace in mind, forgetting about `$x *string` and others.

I'm trying to come up with some other symbol that can't possibly form valid Go, while still being readable and intuitive. Can't find a better one for now.

**Comment by mvdan** [comment]
Both expressions and statements should be working now. It doesn't record previous nodes yet though, so `$x*` will behave like `$_*` for now.
