### ISSUE TITLE
add regex matching (limited to idents)

### ISSUE THREAD

**Issue by mvdan** [mvdan/gogrep#21]
I was using gogrep to easily spot ways to simplify the `cmd/compile/internal/gc` code, which was once C and was transpiled. As such, it has tons of verbosity that is unnecessary.

I was focusing on the following two:

```
i := 0
for _, v := range slice {
    use(i, v)
    i++
}

for _, v := range slice {
    elem := v
    use(elem)
}
```

So, for example, for the first I used `for _, $_ := range $_ { $*_; $_++ }`. It had no false negatives that I can see, but it had one obvious false positive:

```
for _, v := range slice {
    use(v)
    someMap[someKey]++
}
```

You can imagine plenty of others. The root of the problem here is that `$_` in our `$_++` is not limited to just idents, as it can be any expression.

One could say that I should have grepped for `$i := 0; for _, $_ := range $_ { $*_; $i++ }`. But I think that is a worse solution. What if `$i` was actually declared as a parameter, or was of the form `$i = 0` as it was being reused? Or what if it had statements between the decl and the for?

I think this could be orthogonal to #3. That issue is about constraining to `go/types` types, i.e. what the code ends up representing. What I am suggesting here is constraining to `go/ast`, i.e. what type of node it is. The syntax for the two should be different, as `x` could be both an `*ast.Ident` in the AST and be of `*ast.Ident` type in the resulting program.

This could also have other uses. For example, one could easily say "find all for statements whose body starts with an if statement" by constraining the AST type of the first body statement to `IfStmt`. Could still be possible with agressive matching, but this is more direct.

/cc @rogpeppe

**Comment by mvdan** [comment]
I generalised this idea as I was writing the issue, hence the title rewrite.

Ideas for syntax:

* Use different enclosing chars, like `${x Ident}` and `$(x string)`
* Same enclosing chars, but an operator inside, like `$(x | Ident)` and `$(x = string)`

**Comment by mvdan** [comment]
Another less general, but perhaps simpler idea - make all uppercase var names be restricted to idents. That way, `$A` and `$FOO` would only match idents, but `$a` and `$foo` would continue to match any node as it is now. This was my first idea before writing down this proposal, but I don't like it much. Because it is not very generic and because I dislike caps lock.

**Comment by rogpeppe** [comment]
I'm not sure about the idea of exposing AST concepts to the user of this tool. go/ast seems like an implementation detail, and it would be nice if gogrep was accessible to those with Go knowledge but not necessarily any go/ast knowledge. That said, I can see that it would be nice to be able to restrict matches to identifiers only. Another possibility that comes to mind is that of restricting matched nodes to identifiers that match a regular expression. That covers your use case, might potentially be more useful than being able to match other nodes by syntactic type.

For example:

    ${x /.*/}

would match all identifiers.

    ${x /[A-Z].*/

would match all exported identifiers (modulo unicode).

    ${x /i/}

is identical to just `i`.

I'd like to see more use cases for the AST kind restriction.

**Comment by mvdan** [comment]
> go/ast seems like an implementation detail, and it would be nice if gogrep was accessible to those with Go knowledge but not necessarily any go/ast knowledge.

Point taken. This could be bigger towards Go2 if they replace, deprecate or revamp `go/*`. I don't think it would happen in Go2, but I think they want to introduce new API at some point.

> Another possibility that comes to mind is that of restricting matched nodes to identifiers that match a regular expression.

I had thought of the same (e.g. catching all `[Pp]rintf calls`), but not in the sense to use `.*` to match identifiers only.

> ${x /i/}

I'm not going to buy that one too much, as you can simply type `i` in all the occurences. It would be more verbose if the ident gets longer, but it would still be possible. The other two examples make sense.

> I'd like to see more use cases for the AST kind restriction.

I have to admit that matching identifiers only would probably be used more often than all other node types combined. As far as "find one node of this type", all types except `Ident` can currently be done, with small exceptions like `switch { $*_ }` not being possible at the moment.

So the only other use I was thinking of was "any number of nodes of this type". Ultimately, this is to work around the fact that one can only use `*` on `$vars`, not on any node. So potentially, you could do either of these to catch a list of ifs:

    ANY(if $_ { $*_ })
    ${*_ IfStmt}

The former would be more powerful though, as you'd be able to match "any number of" with more filters than just node type, such as `ANY(if $_ { return $*_ })`. So I'd still prefer the former, but I have no idea how to do it cleanly just yet.

As a closing thought, I'd like to get to this (restricting to idents) before #3 because I'd like to see how far this language can go without depending on type information, which is rather expensive at the moment.

**Comment by mvdan** [comment]
Thought some more, and I'm going to do the regex thing with idents. We can always do the node types stuff if it feels necessary after introducing this way to match only idents.
