### ISSUE TITLE
allow 'for $*_ {}' to match 'for {}', 'for x {}' and 'for x; y {}'

### ISSUE THREAD

**Issue by mvdan** [mvdan/gogrep#24]
As a way to get all for loops. For example, say that I wanted to find all for loops with zero breaks:

    gogrep -x 'for $*_ { $*_ }' -v 'break'

Would also apply to places where we can find just an expression, a statement and an expression, or nothign at all, such as `if` or `switch`.

/cc @rogpeppe

**Comment by rogpeppe** [comment]
That sounds reasonable to me. It should probably match similar clauses in switch and if statements too.

**Comment by mvdan** [comment]
This seems easy, but it is slightly tricky as it doesn't fit into our current `stmtList` and `exprList` way of doing things.
