### ISSUE TITLE
Add type constraints

### ISSUE THREAD

**Issue by mvdan** [mvdan/gogrep#3]
Since `$x` can match any node, it can be limiting when matching expressions. For example, we might want to only match strings.

A few syntaxes come to mind, like `$x!string` or `$x: string`.

Here's a thought - what about untyped constants? For example should, `0` match both `int` and `uint`, or neither?

**Comment by rogpeppe** [comment]
I like `$x: string`.

There's also the question of interfaces: should io.Reader match both *bufio.Reader and io.Reader itself?
Could perhaps provide some syntax that can specify exact or assignment-compatible type matching.

For example `x:=io.Reader` to specify exactly io.Reader, vs 'x: io.Reader' to specify anything compatible with io.Reader. Or, maybe the other way around: `x:~io.Reader` could specify anything compatible with io.Reader, leaving `x: io.Reader` to be exact.

**Comment by mvdan** [comment]
That's an interesting approach, and I think it would solve the case of untyped constants too. An untyped (positive) integer constant wouldn't match `int` nor `uint` exactly, but it would 4match both by assignability.

**Comment by rogpeppe** [comment]
I'm no longer convinced about `$x: typeName` - it can match actual Go code, for example `foo{x: y}` matches `$x: y`.

I'm wondering about the following syntax:

- `$x` for a plain wildcard as now.
- `$(x type)` for a type-constrained wildcard
- `$*x` for "any number of of"

Then we don't need the awkward whitespace rule for $* (see issue #10).
Another possibility that might be useful is:

- `$(x "literal string")

where the literal string contains a regular expression to match against literal strings in the program. It's not uncommon to want to search a large program for strings literals of a certain form.

**Comment by mvdan** [comment]
I think you're right - we need less ambiguous syntax. I'm slightly worried about how to combine them, though. If I want to say "any number of strings", would you do `$*(x string)` or `$(*x string)`? I guess the former is a bit more like Go code.

I was also going to suggest using `${x type}` (as in `{` instead of `(`) but I'm thinking it's a bad idea, given that `(x string)` can be valid go, like as a func type result.

**Comment by rogpeppe** [comment]
I'm thinking that `$*(x string)` seems slightly nicer, and agree with your take on round vs squiggly brackets.

**Comment by mvdan** [comment]
Note to self - decide what to do when `$(x type)` matches a non-expression node, such as a statement or a declaration. Possible behaviors that come to mind:

* Grab whatever type is available (e.g. the func signature for a `FuncDecl`) and not match otherwise
* Grab whatever type is available and error otherwise
* Clarify that type constraints can only be used in expressions and error if misused
* Clarify like above, but allow certain node types (such as declarations) as well as expressions

**Comment by mvdan** [comment]
Actually, erroring in these cases could be really bad. If I use `$(x unsafe.Pointer)` to find all unsafe pointers, that would throw so many errors since it would try and fail to match plenty of statement nodes.

**Comment by rogpeppe** [comment]
I think I'd make type-specified wildcards match only expressions, perhaps including type expressions, although I'm not convinced about that.

It might be nice to have a set of possible use cases here.

**Comment by mvdan** [comment]
Here's a thought - how would you express "is a slice", "is a map", "is a pointer" and such? You can't by assignability. Perhaps we should have our own little form of generics for these.

**Comment by mvdan** [comment]
Done for now. May think about the generics mentioned above at some point.
