### ISSUE TITLE
Can't match ` '(a << k) | (a >> (32 - k))' ` with wildcards

### ISSUE THREAD

**Issue by dgryski** [mvdan/gogrep#42]
I was trying to find places where I had rolled my own rotate function instead of using `math/bits`.

I tried this query:
```
gogrep -x  '(a << k) | (a >> (32 - k))' .
```
But it failed to match this code:
```
func rotl32(k uint32, rot uint32) uint32 {
        return (k << rot) | (k >> (32 - rot))
}
```

Note that the equivalent gofmt rewrite query does work:

```
gofmt -d -r '(a << k) | (a >> (32 - k)) -> bits.RotateLeft32(a, k)' .
```

The gogrep query does work if I use the exact same variable names though:
```
gogrep -x '(k << rot) | (k >> (32 - rot))' .
```

**Comment by mvdan** [comment]
Perhaps I'm missing something, but shouldn't that query be using dollar expressions? Otherwise, `a` and `k` are just going to match identifiers with the exact same name.

**Comment by dgryski** [comment]
Yes, because I'm an idiot.

```
 gogrep -x '$a >> $k | $a << (32 - $k)' ./...
```
and
```
gogrep -x '$a >> $k | $a << (64 - $k)' ./...
```

work as expected.  Sorry for the noise.

(Was inspired by https://github.com/golang/go/issues/31456 )

**Comment by mvdan** [comment]
Yay :) you can use `-s` and `-w` to fix the code in-place, by the way. See the README and the tests for some examples. I'd give a working command if I was on the laptop.
