### ISSUE TITLE
$(_ /regexp/) syntax doesn't seem to be working

### ISSUE THREAD

**Issue by quasilyte** [mvdan/gogrep#45]
From the readme:
> `fmt.$(_ /Fprint.*/)(os.Stdout, $*_) // all Fprint* on stdout`

Using the latest gogrep:
```bash
$ gogrep -x 'fmt.$(_ /Fprint.*/)(os.Stdout, $*_)' hello.go
cannot tokenize expr: 1:6: $ must be followed by ident, got (
```
Maybe it's not supposed to be used with `-x`? But I don't see a parser code that handles `/regex/` syntax inside `parse.go` so I'm not sure.

If this feature is not implemented, readme can be adjusted to clarify that.

**Comment by mvdan** [comment]
Whoops, the example is indeed stale. All the "attributes" were moved to the `-a` command, so in your case, you'd want something like:

```
-x 'fmt.$fn(os.Stdout, $*_)' -x '$fn' -a 'rx(`Fprint.*`)'
```

I realise this is a bit clunkier than the original code. I wasn't happy with the original design, and I'm still not happy with the current design. I'm thinking that this would be pretty nice:

```
-x 'fmt.$fn(os.Stdout, $*_)' -a '$fn rx(`Fprint.*`)'
```
