### ISSUE TITLE
no Go files in ...

### ISSUE THREAD

**Issue by kandeshvari** [mvdan/gogrep#58]
I got strange error in the [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) source root

```
$ gogrep -x 'if len($x) < cap($x) { $*_ }'
-: no Go files in /home/me/dev/VictoriaMetrics
```

common grep founds lines correctly:

```
 $ egrep -r 'if len(.+?) < cap(.+?)' .
./app/vmselect/promql/transform.go:	if len(tags) < cap(tags) {
./app/victoria-metrics/self_scraper.go:			if len(mrs) < cap(mrs) {
./app/victoria-metrics/self_scraper.go:	if len(dst) < cap(dst) {
./lib/storage/metric_name.go:	if len(mn.Tags) < cap(mn.Tags) {
./lib/storage/metaindex_row.go:		if len(dst) < cap(dst) {
./lib/mergeset/metaindex_row.go:		if len(dst) < cap(dst) {
./vendor/github.com/klauspost/compress/zstd/history.go:	if len(b) < cap(h.b)-len(h.b) {
```

What I do wrong?

**Comment by kandeshvari** [comment]
Looks like there is no recursive search from the top of the source tree and I need to run this command in every subdir manually. Is there an option for such recurse? `-r` doesn't work.

**Comment by mvdan** [comment]
`gogrep -x 'some pattern' ./...` will do what you want, I'm pretty sure.
